language: generic
os:
 - linux
 - osx
addons:
  homebrew:
    packages:
      - python
      - gcc
install:
 - if [ $TRAVIS_OS_NAME = linux ]; then sudo locale-gen cs_CZ; fi
 - if [ $TRAVIS_OS_NAME = linux ]; then sudo locale-gen cs_CZ.UTF-8; fi
 - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt install -y python3; fi
 - if [ $TRAVIS_OS_NAME = linux ]; then sudo update-locale; fi
 - gcc --std=c99 test_month_names.c
script:
 - export LC_ALL="cs_CZ.UTF-8"
 - python3 test_month_names.py
 - ./a.out
sudo: false
