language: generic
os:
 - linux
 - osx
addons:
  homebrew:
    packages:
      - python
install:
 - "[ $TRAVIS_OS_NAME = linux ] && sudo locale-gen cs_CZ"
 - "[ $TRAVIS_OS_NAME = linux ] && sudo locale-gen cs_CZ.UTF-8"
 - "[ $TRAVIS_OS_NAME = linux ] && sudo apt install -y python3"
 - "[ $TRAVIS_OS_NAME = linux ] && sudo update-locale"
script:
 - python3 test_month_names.py
sudo: false
